[uat-webservers]
172.31.20.73 ansible_user=ec2-user
172.31.31.213 ansible_user=ec2-user

[lb]
172.31.6.182 ansible_user=ubuntu

[db]
172.31.8.37 ansible_user=ubuntu

[db_servers]
172.31.8.37 ansible_user=ubuntu

[webservers]
172.31.20.73 ansible_user=ec2-user
172.31.31.213 ansible_user=ec2-user

[nfs]
172.31.20.73 ansible_user=ec2-user

[all:vars]
ansible_python_interpreter=auto_silent