pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building Stage"'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing Stage"'
                }
            }
        }

        stage('package') {
            steps {
                script {
                    sh 'echo "Packaging Stage"'
                }
            }
        } 


         stage('Deploy') {
            steps {
                script {
                    sh 'echo "Deploying Stage"'
                }
            }
        }
        
         stage('Finish and Cleanup') {
            steps {
                script {
                    sh 'echo "Finish and Cleanup Stage"'
                }
            }
        }
    }
}
