pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    stages {
        stage('Initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/Aexite1/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
            }
        }

        stage('Test SSH Connections') {
           steps {
             script {
                sshagent(['private-key']) { // Using your existing Jenkins credentials ID
                // -n redirects stdin from /dev/null to prevent interactive hanging
                // -o BatchMode=yes disables interactive prompting completely
                // timeout 5 forces Linux to drop the command if it lags for 5 seconds
                sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@172.31.8.37 exit"
                sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@172.31.6.182 exit"
                sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ec2-user@172.31.20.73 exit"
                sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ec2-user@172.31.31.213 exit"
                    }
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                sshagent(['private-key']) {
                    ansiblePlaybook(
                        become: true,
                        credentialsId: 'private-key',
                        disableHostKeyChecking: true,
                        installation: 'ansible',
                        inventory: '${WORKSPACE}/inventory/dev.yml',
                        playbook: '${WORKSPACE}/playbooks/site.yml'
                    )
                }
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}