pipeline {
    agent any

    parameters {
        string(name: 'inventory', defaultValue: 'dev.yml', description: 'This is the inventory file for the environment to deploy configuration')
        string(name: 'ansible_tags', defaultValue: 'webserver', description: 'Ansible tags to run specific roles or tasks')
    }

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
        // 🛠️ Forces Ansible to locate your root roles directory
        ANSIBLE_ROLES_PATH = "${WORKSPACE}/roles"
    }

    stages {
        stage('Initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/Aexite1/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
            }
        }

        stage('Test SSH Connections') {
            steps {
                script {
                    sshagent(['private-key']) { 
                        sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@172.31.8.37 exit"
                        sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@172.31.6.182 exit"
                        sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ec2-user@172.31.20.73 exit"
                        sh "timeout 5 ssh -n -o BatchMode=yes -o StrictHostKeyChecking=no ec2-user@172.31.31.213 exit"
                    }
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                sshagent(['private-key']) {
                    ansiblePlaybook(
                        become: true,
                        credentialsId: 'private-key',
                        disableHostKeyChecking: true,
                        installation: 'ansible',
                        inventory: "${WORKSPACE}/inventory/${inventory}",
                        playbook: "${WORKSPACE}/playbooks/site.yml",
                        tags: "${params.ansible_tags}"
                    )
                }
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}
