---
- name: Include dynamic variables
  hosts: all
  become: true
  tasks:
    - name: Load dynamic environment variables
      ansible.builtin.include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- name: Import common baseline configuration
  ansible.builtin.import_playbook: ../static-assignments/common.yml

- name: Import UAT webservers configuration
  ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml
  tags:
 - webservers


- name: Import loadbalancers configuration
  ansible.builtin.import_playbook: ../static-assignments/loadbalancer.yml
  tags:
 - nginx_lb

- name: Import Database configuration
  ansible.builtin.import_playbook: ../static-assignments/db-servers.yml
  tags:
    - db


- name: Configure Load Balancer and Apache
  hosts: lb
  become: true
  roles:
    - nginx
    - apache
